server {
	listen 80;
	server_name _;
	root /var/www/html/www;
	index index.php;

	server_tokens off;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location = /sw.js {
		add_header Cache-Control "no-cache";
		try_files $uri =404;
	}

	location = /manifest.json {
		types { }
		default_type application/manifest+json;
		add_header Cache-Control "no-cache";
		try_files $uri =404;
	}

	location ~* \.(png|svg|ico|webp)$ {
		add_header Cache-Control "public, max-age=604800";
		try_files $uri =404;
	}
	location ~* \.(css|js)$ {
		add_header Cache-Control "public, max-age=3600";
		try_files $uri =404;
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param DOCUMENT_ROOT $document_root;
	}
}
